import { Inter } from "next/font/google";

 import "./globals.css";
import {Navbar} from '@/components/index';
// import Font Awesome CSS
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;


 
 const inter = Inter({ subsets: ["latin"] });
 
 export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  title: "movies",
  description: "new movies",
 };
 
 export default function RootLayout({ children }) {
   return (
     <html lang="en">
      <body className={inter.className}>
        <header >
          <Navbar />
        </header>
        {children}
      </body>
     </html>
   );
 }